from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        raise RuntimeError(f"anchor not found: {label}")
    return text.replace(old, new, 1)


# Intelligence V3
p = Path("app/astrology/features/marriage_question_intelligence_v3.py")
s = p.read_text(encoding="utf-8")
s = replace_once(s, '    "married_life_quality": (\n        "Married Life / Relationship Quality"\n    ),\n', '    "married_life_quality": (\n        "Married Life / Relationship Quality"\n    ),\n    "relationship_challenges": (\n        "Relationship Challenges / Stress & Repair"\n    ),\n', "intelligence label")
helper = '''\n\n# =========================================================\n# RELATIONSHIP CHALLENGES DETECTION\n# =========================================================\n\ndef _detect_relationship_challenges(question: str) -> dict[str, Any] | None:\n    patterns = (\n        (r"\\b(?:marriage|relationship)\\s+(?:conflict|conflicts|fights?|arguments?)\\b", "relationship conflict"),\n        (r"\\b(?:conflict|fights?|arguments?)\\s+in\\s+(?:my\\s+)?(?:marriage|relationship)\\b", "relationship conflict"),\n        (r"\\bemotional(?:ly)?\\s+(?:distance|distant|withdrawal|withdrawn)\\b", "emotional distance"),\n        (r"\\b(?:unstable|instability|unpredictable)\\s+(?:marriage|relationship)\\b", "relationship instability"),\n        (r"\\b(?:marriage|relationship)\\s+(?:unstable|instability|unpredictable)\\b", "relationship instability"),\n        (r"\\bcommitment\\s+(?:delay|delays|pressure|difficulty|difficulties)\\b", "commitment pressure"),\n        (r"\\b(?:repair|reconcile|reconciliation|recover)\\b.{0,24}\\b(?:marriage|relationship)\\b", "relationship repair"),\n        (r"\\b(?:marriage|relationship)\\b.{0,24}\\b(?:repair|reconcile|reconciliation|recover)\\b", "relationship repair"),\n        (r"\\brelationship\\s+challenges?\\b", "relationship challenges"),\n        (r"\\bmarital\\s+(?:conflict|stress|challenges?)\\b", "marital challenges"),\n    )\n    matched = []\n    for pattern, label in patterns:\n        if re.search(pattern, question) and label not in matched:\n            matched.append(label)\n    if not matched:\n        return None\n    return {"event": "relationship_challenges", "event_label": EVENT_LABELS["relationship_challenges"], "matched_keywords": matched}\n'''
s = replace_once(s, '\n# =========================================================\n# SPECIAL EVENT DETECTION\n# =========================================================\n', helper + '\n# =========================================================\n# SPECIAL EVENT DETECTION\n# =========================================================\n', "helper insertion")
s = replace_once(s, '    married_life_quality = _detect_married_life_quality(question)\n    if married_life_quality:\n        detected.append(married_life_quality)\n', '    relationship_challenges = _detect_relationship_challenges(question)\n    if relationship_challenges:\n        detected.append(relationship_challenges)\n\n    married_life_quality = _detect_married_life_quality(question)\n    if married_life_quality:\n        detected.append(married_life_quality)\n', "detector call")
s = replace_once(s, '        if (\n            "married_life_quality" in special_names\n            and event_name in ("general_marriage", "relationship_stability", "marriage_timing")\n        ):\n            continue\n', '        if (\n            "relationship_challenges" in special_names\n            and event_name in ("general_marriage", "relationship_stability", "marriage_delay_challenge", "marriage_timing")\n        ):\n            continue\n\n        if (\n            "married_life_quality" in special_names\n            and event_name in ("general_marriage", "relationship_stability", "marriage_timing")\n        ):\n            continue\n', "base cleanup")
s = replace_once(s, '        "spouse_family_background",\n        "married_life_quality",\n', '        "spouse_family_background",\n        "relationship_challenges",\n        "married_life_quality",\n', "priority")
p.write_text(s, encoding="utf-8")


# Router V3
p = Path("app/astrology/features/marriage_forecast_router_v3.py")
s = p.read_text(encoding="utf-8")
s = replace_once(s, 'from app.astrology.features.married_life_quality_reasoning_v2 import (\n    analyze_married_life_quality_v2,\n)\n', 'from app.astrology.features.married_life_quality_reasoning_v2 import (\n    analyze_married_life_quality_v2,\n)\n\nfrom app.astrology.features.relationship_challenges_reasoning_v2 import (\n    analyze_relationship_challenges_v2,\n)\n', "router import")
s = replace_once(s, '    "married_life_quality": (\n        "Married Life / Relationship Quality"\n    ),\n', '    "married_life_quality": (\n        "Married Life / Relationship Quality"\n    ),\n    "relationship_challenges": (\n        "Relationship Challenges / Stress & Repair"\n    ),\n', "router label")
route_fn = '''\n\n# =========================================================\n# RELATIONSHIP CHALLENGES ROUTE\n# =========================================================\n\ndef _route_relationship_challenges(chart: dict[str, Any], question_analysis: dict[str, Any], reference_moment: datetime) -> dict[str, Any]:\n    intent = _safe_dict(question_analysis.get("intent"))\n    question = str(question_analysis.get("original_question", question_analysis.get("normalised_question", "")) or "")\n    analysis = analyze_relationship_challenges_v2(chart, question)\n    result = {\n        "available": bool(analysis.get("available")), "route": "natal_evidence", "event": "relationship_challenges",\n        "event_label": EVENT_LABELS["relationship_challenges"], "question_type": intent.get("question_type"),\n        "direction": intent.get("direction"), "parser_confidence": intent.get("confidence"),\n        "reference_moment": reference_moment.isoformat(), "evidence_engine": "relationship_challenges_reasoning_v2",\n        "forecast_type": "natal_pattern", "model_version": analysis.get("model_version"),\n        "question": analysis.get("question", question), "normalised_question": analysis.get("normalised_question"),\n        "target": analysis.get("target"), "target_label": analysis.get("target_label"),\n        "matched_keywords": analysis.get("matched_keywords", []), "support_score": analysis.get("support_score"),\n        "support_level": analysis.get("support_level"), "support_label": analysis.get("support_label"),\n        "confidence": analysis.get("confidence"), "answer": analysis.get("answer"), "summary": analysis.get("summary"),\n        "limitation": analysis.get("limitation"), "strongest_themes": analysis.get("strongest_themes", []),\n        "evidence_count": analysis.get("evidence_count", 0), "evidence": analysis.get("evidence", []),\n        "natal_profile": analysis.get("natal_profile", {}), "analysis": analysis,\n    }\n    if not analysis.get("available"):\n        result["reason"] = analysis.get("reason")\n    return result\n'''
s = replace_once(s, '\n# =========================================================\n# SPOUSE PROFESSION TARGET DETECTION\n# =========================================================\n', route_fn + '\n# =========================================================\n# SPOUSE PROFESSION TARGET DETECTION\n# =========================================================\n', "route insertion")
s = replace_once(s, '    elif inherited_event == (\n        "married_life_quality"\n    ):\n\n        result = _route_married_life_quality(chart, inherited_analysis, reference_moment)\n', '    elif inherited_event == (\n        "married_life_quality"\n    ):\n\n        result = _route_married_life_quality(chart, inherited_analysis, reference_moment)\n\n    elif inherited_event == (\n        "relationship_challenges"\n    ):\n\n        result = _route_relationship_challenges(chart, inherited_analysis, reference_moment)\n', "follow-up dispatch")
s = replace_once(s, '    if query_mode == "single_event" and event_name == "married_life_quality":\n        return _route_married_life_quality(chart, question_analysis, reference_moment)\n', '    if query_mode == "single_event" and event_name == "married_life_quality":\n        return _route_married_life_quality(chart, question_analysis, reference_moment)\n\n    if query_mode == "single_event" and event_name == "relationship_challenges":\n        return _route_relationship_challenges(chart, question_analysis, reference_moment)\n', "main dispatch")
p.write_text(s, encoding="utf-8")
